# Generated by Django 2.2.13 on 2020-08-29 15:59

from django.db import migrations


def set_multi_partner(apps, schema_editor):
    Partner = apps.get_model('partner', 'Partner')
    multi = Partner(code='multi',name='multi')
    multi.save()


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_multi_partner),
    ]
