# Generated by Django 2.2.13 on 2020-08-04 09:30

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('content', '0006_auto_20200804_0908'),
        ('catalogue', '0002_auto_20200804_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='content.ContentProductTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
