# Generated by Django 2.2.13 on 2020-08-04 09:47

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='content.ContentProductTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
