# Generated by Django 2.2.13 on 2020-08-04 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basket', '0002_auto_20200804_0805'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.ContentProjet'),
        ),
    ]
