#!/bin/bash

# Setup venv
virtualenv ../venv

# install dependancies
source ../venv/bin/activate
pip install -r requirements.txt

# make migrations
python manage.py migrate

# load countries
python manage.py oscar_populate_countries

# load shipping events
sqlite3 db.sqlite3  "INSERT INTO order_shippingeventtype (name, code) VALUES ('expédié', 'liv01');"
sqlite3 db.sqlite3  "INSERT INTO order_shippingeventtype (name, code) VALUES ('livré', 'liv02');"

# load categories
python manage.py loaddata catalogue.json 
