# Generated by Django 2.2.13 on 2020-07-20 16:24

from django.db import migrations


def set_default_categories(apps, schema_editor):
    BlogPageCategory = apps.get_model('blog', 'BlogPageCategory')
    categories = [
        'Association',
        'Partenaire',
        'Projet'
    ]
    
    for c in categories:
        category = BlogPageCategory(name=c)
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_default_categories),
    ]
