# Generated by Django 2.2.13 on 2020-07-20 18:01

from django.db import migrations


def set_default_categories(apps, schema_editor):
    BlogPageCategory = apps.get_model('blog', 'BlogPageCategory')
    categories = [
        'Association',
        'Partenaire',
        'Projet'
    ]
    
    for c in categories:
        category = BlogPageCategory(name=c)
        category.save()
        
def drop_welcome_page(apps, schema_editor):
    Page = apps.get_model('wagtailcore', 'Page')
    welcome_page = Page.objects.get(title='Welcome to your new Wagtail site!')
    welcome_page.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_default_categories),
        migrations.RunPython(drop_welcome_page),
    ]
