# Generated by Django 2.2.13 on 2020-08-04 08:47

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200804_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='content.ContentPage'),
        ),
        migrations.AlterField(
            model_name='contentproducttag',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='catalogue.Product'),
        ),
    ]
