# Generated by Django 2.2.13 on 2020-08-04 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20200804_0805'),
        ('content', '0004_auto_20200804_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentproducttag',
            name='content_object',
        ),
        migrations.AddField(
            model_name='contentproducttag',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Product'),
        ),
    ]
