# Generated by Django 2.2.13 on 2020-08-04 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_product_tags'),
        ('content', '0006_auto_20200804_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentproducttag',
            name='content_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product'),
        ),
        migrations.AlterField(
            model_name='contentproducttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_contentproducttag_items', to='taggit.Tag'),
        ),
    ]
