# Generated by Django 2.2.13 on 2020-08-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20200804_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentproducttag',
            name='content_object',
        ),
    ]
