# Generated by Django 2.2.13 on 2020-08-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_contentproducttag_content_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentproducttag',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
