# Generated by Django 2.2.13 on 2020-08-04 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_product_tags'),
        ('content', '0009_contentproducttag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentproducttag',
            name='name',
        ),
        migrations.AddField(
            model_name='contentproducttag',
            name='content_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='catalogue.Product'),
        ),
    ]
