# Generated by Django 2.2.13 on 2020-08-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20200805_0823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketplaceConfig',
        ),
    ]
