# Generated by Django 2.2.13 on 2020-08-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0022_uploadedimage'),
        ('content', '0013_socialmediasettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialMediaSettings',
            new_name='MarketplaceSettings',
        ),
    ]
