# Generated by Django 2.2.13 on 2020-08-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20200805_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacesettings',
            name='test',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
