# Generated by Django 2.2.13 on 2020-08-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_marketplacesettings_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketplaceSettings',
        ),
    ]
