# Generated by Django 2.2.13 on 2020-08-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_delete_marketplacesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentasso',
            options={'verbose_name': 'Page - Association'},
        ),
        migrations.AlterModelOptions(
            name='contentindexcategorypage',
            options={'verbose_name': 'Index - Catégories'},
        ),
        migrations.AlterModelOptions(
            name='contentindexpage',
            options={'verbose_name': 'Index - Standard'},
        ),
        migrations.AlterModelOptions(
            name='contentpage',
            options={'verbose_name': 'Page - Standard'},
        ),
        migrations.AlterModelOptions(
            name='contentpartner',
            options={'verbose_name': 'Page - Partenaire'},
        ),
        migrations.AlterModelOptions(
            name='contentprojet',
            options={'verbose_name': 'Page - Projet'},
        ),
        migrations.AlterModelOptions(
            name='contenttagindexpage',
            options={'verbose_name': 'Index - Tags'},
        ),
    ]
