# Generated by Django 2.2.13 on 2020-08-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_contentindexproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentprojet',
            name='achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentprojet',
            name='achievement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
