# Generated by Django 2.2.13 on 2020-08-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20200824_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentprojet',
            name='achievement_percent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
