# Generated by Django 2.2.13 on 2020-08-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_auto_20200824_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentprojet',
            name='achievement_percent',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
    ]
