# Generated by Django 2.2.13 on 2020-08-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_auto_20200825_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentprojet',
            name='donation_count',
            field=models.IntegerField(default=1),
        ),
    ]
