# Generated by Django 2.2.13 on 2020-08-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_contentprojet_donation_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentprojet',
            name='donation_count',
            field=models.IntegerField(default=0),
        ),
    ]
