# Generated by Django 2.2.13 on 2020-08-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_auto_20200830_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentindexasso',
            name='intro',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contentindexproject',
            name='intro',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
