# Generated by Django 2.2.13 on 2020-08-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_auto_20200830_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentindexasso',
            name='intro',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contentindexproject',
            name='intro',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
