# Generated by Django 2.2.13 on 2020-08-05 16:28

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_delete_marketplacesettings'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacesettings',
            name='product_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='content.ContentPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
