# Generated by Django 2.2.13 on 2020-08-05 16:33

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20200804_0947'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('settings', '0003_remove_marketplacesettings_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_settingproducttag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='marketplacesettings',
            name='product_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='settings.SettingProductTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
