# Generated by Django 2.2.13 on 2020-08-06 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_delete_marketplacesettings'),
        ('settings', '0006_auto_20200806_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacesettings',
            name='product_tags',
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='menu_tag_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Tag'),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='menu_tag_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Tag'),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='menu_tag_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Tag'),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='menu_tag_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Tag'),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='menu_tag_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Tag'),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='menu_tag_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Tag'),
        ),
    ]
