# Generated by Django 2.2.13 on 2020-08-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_auto_20200806_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacesettings',
            name='menu_label_1',
            field=models.CharField(max_length=30, null=True, verbose_name='Label 1'),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='menu_label_2',
            field=models.CharField(max_length=30, null=True, verbose_name='Label 2'),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='menu_label_3',
            field=models.CharField(max_length=30, null=True, verbose_name='Label 3'),
        ),
        migrations.AlterField(
            model_name='marketplacesettings',
            name='menu_url_1',
            field=models.URLField(null=True, verbose_name='URL 1'),
        ),
        migrations.AlterField(
            model_name='marketplacesettings',
            name='menu_url_2',
            field=models.URLField(null=True, verbose_name='URL 2'),
        ),
        migrations.AlterField(
            model_name='marketplacesettings',
            name='menu_url_3',
            field=models.URLField(null=True, verbose_name='URL 3'),
        ),
    ]
