# Generated by Django 2.2.13 on 2020-08-06 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_auto_20200806_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacesettings',
            name='menu_label_1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Label 1'),
        ),
        migrations.AlterField(
            model_name='marketplacesettings',
            name='menu_label_2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Label 2'),
        ),
        migrations.AlterField(
            model_name='marketplacesettings',
            name='menu_label_3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Label 3'),
        ),
        migrations.AlterField(
            model_name='marketplacesettings',
            name='menu_tag_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Tag'),
        ),
        migrations.AlterField(
            model_name='marketplacesettings',
            name='menu_tag_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Tag'),
        ),
        migrations.AlterField(
            model_name='marketplacesettings',
            name='menu_tag_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Tag'),
        ),
        migrations.AlterField(
            model_name='marketplacesettings',
            name='menu_tag_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Tag'),
        ),
        migrations.AlterField(
            model_name='marketplacesettings',
            name='menu_tag_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Tag'),
        ),
        migrations.AlterField(
            model_name='marketplacesettings',
            name='menu_tag_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.Tag'),
        ),
        migrations.AlterField(
            model_name='marketplacesettings',
            name='menu_url_1',
            field=models.URLField(blank=True, null=True, verbose_name='URL 1'),
        ),
        migrations.AlterField(
            model_name='marketplacesettings',
            name='menu_url_2',
            field=models.URLField(blank=True, null=True, verbose_name='URL 2'),
        ),
        migrations.AlterField(
            model_name='marketplacesettings',
            name='menu_url_3',
            field=models.URLField(blank=True, null=True, verbose_name='URL 3'),
        ),
    ]
