# Generated by Django 2.2.13 on 2020-08-17 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('settings', '0014_auto_20200806_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacesettings',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Favicon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
