# Generated by Django 2.2.13 on 2020-08-17 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_auto_20200817_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacesettings',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Favicon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
