# Generated by Django 2.2.13 on 2020-08-19 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_contentindexasso'),
        ('settings', '0018_auto_20200817_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplacesettings',
            options={'verbose_name': 'Parametres site'},
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='index_asso',
            field=models.ForeignKey(blank=True, help_text="Lien vers l'index des associations", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.ContentPage'),
        ),
        migrations.AlterField(
            model_name='marketplacesettings',
            name='menu_url_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL 1'),
        ),
    ]
