# Generated by Django 2.2.13 on 2020-08-19 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_auto_20200819_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacesettings',
            name='index_asso',
            field=models.ForeignKey(blank=True, help_text="Lien vers l'index des associations", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.ContentIndexAsso'),
        ),
    ]
