# Generated by Django 2.2.13 on 2020-08-22 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_contentindexproject'),
        ('settings', '0020_auto_20200819_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacesettings',
            name='index_project',
            field=models.ForeignKey(blank=True, help_text="Lien vers l'index des projets", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.ContentIndexAsso'),
        ),
    ]
