# Generated by Django 2.2.13 on 2020-08-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0022_auto_20200822_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacesettings',
            name='sous_titre_marketplace',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sous-titre de la marketplace'),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='titre_marketplace',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Titre de la marketplace'),
        ),
    ]
