# Generated by Django 2.2.12 on 2020-05-06 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='partner',
            field=models.ForeignKey(db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to='partner.Partner', verbose_name='Partner'),
        ),
    ]
