# Generated by Django 2.2.13 on 2020-07-28 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200721_1556'),
        ('order', '0002_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.BlogProjet'),
        ),
    ]
